version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
      - run: npm run lint
      - run:
          name: "Testing"
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./test-results/unit-tests"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
