version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
      - run: npm run lint
      - run:
          name: "Testing"
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run: npm run docs
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release
      - run: npm run docs
      - run: npm run docs:deploy

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
